### PR TITLE
Add more websites to Portuguese

### PR DESCRIPTION
**Pull request by mgoulao**

### CODE REVIEW

**Review by thunderpoot — CHANGES_REQUESTED** [review]
Thank you @mgoulao for your contributions. These additions could benefit from parenthetical descriptions, particularly for the "Government" section, since POR is spoken in many places around the world.

**Comment by mgoulao** [comment]
Yes, that makes sense.
Something like this?
```
Culture / History:
- Portugal
  - https://www.museusemonumentos.pt/pt
  - etc.

Government:
- Portugal
  - https://www.portugal.gov.pt/pt/gc24
  - etc.
```

**Comment by thunderpoot** [comment]
> Yes, that makes sense. Something like this?
> 
> ```
> Culture / History:
> - Portugal
>   - https://www.museusemonumentos.pt/pt
>   - etc.
> 
> Government:
> - Portugal
>   - https://www.portugal.gov.pt/pt/gc24
>   - etc.
> ```

This isn't a strict requirement for all URLs, but the convention is to add comments and descriptions in parentheses after the URL itself, on the same line, such as:

```md
Culture / History:
- https://www.museusemonumentos.pt/pt (Portugal’s Museums and Monuments)
```

```md
Government:
- https://www.portugal.gov.pt/pt/gc24 (Official portal of the Government of Portugal)
```

This way all of these files can be easily parsed by us later when adding the URLs to our seed list.

See this example in the `welsh.md` file:
https://github.com/commoncrawl/web-languages/blob/176d6c22ef06e347eb3b1da016c152720b6394d5/living/welsh.md?plain=1#L12-L17

**Review by thunderpoot — APPROVED** [review]
Thank you very much for addressing the review comments, @mgoulao.

**Pull request merged**
